### PR TITLE
fastify v4 support

### PR DESCRIPTION
**Pull request by artiz**
Migrated plugin to fastify v4, planning to create new @fastify/oas @fastify/oas package to use with fastify v4

### CODE REVIEW

**Comment by niels-bosman** [comment]
Why isn't this PR merged yet? @SkeLLLa Current package does NOT work with fastify 4.X

**Comment by kgoedecke** [comment]
@artiz can we merge this?

**Comment by artiz** [comment]
> @SkeLLLa @artiz can we merge this?
Of course

**Comment by SkeLLLa** [comment]
This plugin is deprecated in favor of fastify-swagger. Openapi was added to fastify swagger and it supports more features, so there's no reason to maintain this one.

This plugin doesn't fully support fastify v3 because of different schema parsing. And this PR also doesn't add such functionality. Plus fastify v4 has onRoute behavior, so current route crowing logic likely will not work.

So if you want to maintain it's better to make a fork and publish it as separate package.

**Comment by kgoedecke** [comment]
@SkeLLLa would be great if you could add a note on that in the `README.md`.

**Pull request closed without merging**
